### ISSUE TITLE
Envoy 1.24.0 release

### ISSUE THREAD

**Issue by RafalGoslawski** [tetratelabs/archive-envoy#45]
Envoy 1.24 has been released ~2 weeks ago. It would be great if you'd archive the binaries, as the repos you maintain are very handy.

Thanks for keeping the archive!

**Comment by codefromthecrypt** [comment]
Good point. I'll do it

@dussab I'm wondering if we shouldn't open this repository to outside contributors. It has been routine that folks have had to ask because no-one watches it. Clicking release is very easy, but it is annoying for end users to have to ask each time. wdyt?

**Comment by codefromthecrypt** [comment]
I just clicked to have the "release" action go on v1.24.0 (windows, linux, Darwin) and v1.24.0_debug (linux)

Darwin will fail because home-brew isn't working, yet and it is still the case Envoy doesn't release binaries for Darwin.
Good news is it is in progress as @dio started it last week. maybe you can watch/ping here if you need darwin/osx https://github.com/Homebrew/homebrew-core/pull/114194 

Once the above is done, someone can re-do the v1.24.0 release action and it will archive darwin.

**Comment by mathetake** [comment]
I believe it's been released by @dio !
